global:
  params:
    p2: global-2
    p1: global-1-updated
management:
  endpoints:
    web:
      exposure:
        include: health,refresh
spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
