spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/billing-db?createDatabaseIfNotExist=true
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    rest:
      base-path: /api