spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    rest:
      base-path: /api
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/customer-db?createDatabaseIfNotExist=true
customer:
  params:
    x: finally_it_worked
    y: finally_it_worked